<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>MJ Node · __NODE__</title>
<style>:root{--bg:#F3F5F2;--pan:#fff;--ink:#16211E;--mut:#5F6E69;--line:#D9DFDB;--pine:#0F4C42;--brass:#B8862B;--ok:#2E7D4F;--bad:#B3412E}
@media(prefers-color-scheme:dark){:root{--bg:#0F1514;--pan:#161E1C;--ink:#E6ECE9;--mut:#93A29C;--line:#26332F;--pine:#5FB59F;--brass:#D4A74A;--ok:#5DB985;--bad:#E1705B}}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:15px/1.5 "Hind Siliguri",system-ui,sans-serif}
.top{background:#0F4C42;color:#fff;padding:10px 16px;display:flex;gap:12px;align-items:center;flex-wrap:wrap}.top b{font-size:18px}.top small{opacity:.8;display:block}.top .r{margin-left:auto;display:flex;gap:6px}
button,input,select{font:inherit;padding:7px 10px;border-radius:6px;border:1px solid var(--line);background:var(--pan);color:var(--ink)}button{cursor:pointer}.top button{background:none;color:#fff;border-color:#fff6}.top button.on{background:var(--brass);border-color:var(--brass)}
#lg{max-width:360px;margin:12vh auto;padding:22px;background:var(--pan);border:1px solid var(--line);border-radius:8px;display:grid;gap:10px}#lg h1{margin:0;font-size:20px;color:var(--pine)}#lg button{background:var(--pine);color:#fff;border:0;font-weight:700}#er{color:var(--bad);margin:0}
main{max-width:1000px;margin:0 auto;padding:16px}h2{font-size:18px;margin:22px 0 8px}.card{background:var(--pan);border:1px solid var(--line);border-radius:8px;padding:12px}
ul.t{list-style:none;padding-left:18px;margin:0;border-left:1px solid var(--line)}ul.t.root{border:0;padding:0}.n{display:flex;gap:8px;align-items:baseline;flex-wrap:wrap;padding:4px 0}.lv{font-size:11px;background:var(--pine);color:#fff;border-radius:4px;padding:0 6px}
.sc{margin-left:auto;font-weight:700;border-radius:10px;padding:0 10px;border:1px solid var(--line)}.g{color:var(--ok)}.y{color:var(--brass)}.r2{color:var(--bad)}
table{width:100%;border-collapse:collapse;font-size:13px}td,th{text-align:left;padding:5px 8px;border-bottom:1px solid var(--line);vertical-align:top}.id{font:12px ui-monospace,monospace;color:var(--pine)}.h{font:11px ui-monospace,monospace;color:var(--mut)}
.v{padding:10px 14px;border-radius:8px;border:1px solid var(--line);margin-bottom:8px}.v.ok{border-color:var(--ok);color:var(--ok)}.v.no{border-color:var(--bad);color:var(--bad);font-weight:700}.tw{overflow:auto}</style></head><body>
<div id="lg"><h1>MJ Node · __NODE__</h1><input id="u" placeholder="User ID / ইউজার আইডি" autocomplete="username"><input id="p" type="password" placeholder="Password / পাসওয়ার্ড" autocomplete="current-password"><button id="go">Open / খুলুন</button><p id="er"></p></div>
<div id="app" hidden><div class="top"><div><b id="hn"></b><small id="hs"></small></div><div class="r"><button data-l="en">EN</button><button data-l="bn">BN</button><button id="out"></button></div></div>
<main><div id="vf"></div><h2 id="h1"></h2><div class="card" id="tr"></div><h2 id="h2"></h2><div class="card"><input id="q" style="width:60%"> <select id="k"></select></div><div class="tw card"><table id="lt"></table></div></main></div>
<script>const PK=__PACKS__;let P,lang='en';const $=s=>document.querySelector(s),enc=new TextEncoder(),b64=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0)),hex=b=>[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('');
const sha=async s=>hex(await crypto.subtle.digest('SHA-256',enc.encode(s))),canon=o=>Array.isArray(o)?'['+o.map(canon).join(',')+']':o&&typeof o==='object'?'{'+Object.keys(o).sort().map(k=>JSON.stringify(k)+':'+canon(o[k])).join(',')+'}':JSON.stringify(o);
const cat=(a,b)=>{const r=new Uint8Array(a.length+b.length);r.set(a);r.set(b,a.length);return r};
async function openPack(uid,pw){const k=PK.find(x=>x.u===uid.trim().toUpperCase());if(!k)throw 0;
const bits=await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt:b64(k.s),iterations:200000},await crypto.subtle.importKey('raw',enc.encode(pw),'PBKDF2',false,['deriveBits']),512);
const im=r=>crypto.subtle.importKey('raw',r,{name:'HMAC',hash:'SHA-256'},false,['sign','verify']),ek=await im(bits.slice(0,32)),mk=await im(bits.slice(32)),n=b64(k.n),c=b64(k.c);
if(!await crypto.subtle.verify('HMAC',mk,b64(k.m),cat(n,c)))throw 0;const out=new Uint8Array(c.length);
for(let i=0;i<c.length;i+=32*256){const bl=[];for(let j=i;j<Math.min(c.length,i+32*256);j+=32)bl.push(crypto.subtle.sign('HMAC',ek,cat(n,new Uint8Array([j/32>>>24&255,j/32>>>16&255,j/32>>>8&255,j/32&255]))));
(await Promise.all(bl)).forEach((s,q)=>{const o=i+q*32,s8=new Uint8Array(s);for(let z=0;z<32&&o+z<c.length;z++)out[o+z]=c[o+z]^s8[z]})}
return JSON.parse(new TextDecoder().decode(out))}
async function verify(P){const by={},bad=[],miss=[],ids=new Set(P.nodes.map(x=>x.id));P.ledger.filter(e=>ids.has(e.node)).forEach(e=>(by[e.node]=by[e.node]||[]).push(e));
for(const ch of Object.values(by)){let pv='0'.repeat(64);for(const e of ch){const{hash,...b}=e;if(e.prev!==pv||await sha(canon(b))!==hash){bad.push(e.id);break}pv=hash}}
const an=P.ledger.filter(e=>e.kind==='anchor').pop();if(an)for(const[nd,h]of Object.entries(an.data.heads))if(by[nd]&&!by[nd].some(e=>e.hash===h))miss.push(nd);return{bad,miss,n:P.ledger.length,an:!!an}}
const L={en:{tree:'Network & accountability scores',led:'Ledger (append-only)',q:'Search…',all:'All kinds',out:'Logout',ok:'Verified: all hash chains intact',no:'TAMPERING DETECTED in',anc:'Anchored to Central ✓',nanc:'no Central anchor yet',ent:'entries',ld:'Leader'},
bn:{tree:'নেটওয়ার্ক ও জবাবদিহিতার স্কোর',led:'লেজার (শুধু যুক্ত হয়, মোছা যায় না)',q:'খুঁজুন…',all:'সব ধরন',out:'লগআউট',ok:'যাচাইকৃত: সব হ্যাশ চেইন অক্ষুণ্ণ',no:'ছেঁড়াছেঁড়া/পরিবর্তন ধরা পড়েছে:',anc:'কেন্দ্রীয় অ্যাঙ্কর মিলেছে ✓',nanc:'এখনো কেন্দ্রীয় অ্যাঙ্কর নেই',ent:'এন্ট্রি',ld:'দায়িত্বশীল'}};
const esc=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c])),pk=(a,b)=>lang==='bn'?(b||a):(a||b),T=()=>L[lang];let V;
function sum(e){const d=e.data;return e.kind==='dist'?`${esc(d.item)} × ${d.qty} → ${esc(d.recipient)} ${esc(d.serial||'')}`:e.kind==='eval'?`→ ${d.of}: <b>${d.score}/100</b> ${esc(d.text)} <span class="h">[${d.basis.join(', ')}]</span>`:e.kind==='task'?`→ ${d.to}: ${esc(d.title)} (due ${d.due})`:e.kind==='anchor'?'heads of '+Object.keys(d.heads).length+' chains':esc(d.text||d.en||d.id||'')+(e.ref?` <span class="h">↪ ${e.ref}</span>`:'')}
function draw(){const t=T(),R=P.nodes.find(x=>x.id===P.root);document.documentElement.lang=lang;
$('#hn').textContent='MJ Node · '+pk(R.en,R.bn);$('#hs').textContent=`${P.lv[R.level][0]} ${R.id} · ${t.ld}: ${R.leader}`+(P.anc.length?' · ↑ '+P.anc.map(a=>a.id).join(' › '):'');
document.querySelectorAll('[data-l]').forEach(b=>b.classList.toggle('on',b.dataset.l===lang));$('#out').textContent=t.out;$('#h1').textContent=t.tree;$('#h2').textContent=t.led;$('#q').placeholder=t.q;
const ks=[...new Set(P.ledger.map(e=>e.kind))],cur=$('#k').value;$('#k').innerHTML=`<option value="">${t.all}</option>`+ks.map(k=>`<option>${k}</option>`).join('');$('#k').value=cur;
const cnt={};P.ledger.forEach(e=>cnt[e.node]=(cnt[e.node]||0)+1);
const tr=i=>{const n=P.nodes.find(x=>x.id===i),s=P.scores[i],c=s==null?'':s>=75?'g':s>=50?'y':'r2';return`<li><div class="n"><span class="lv">${P.lv[n.level][lang==='bn'?2:1]}</span><b>${esc(pk(n.en,n.bn))}</b><span class="id">${n.id}</span><span>${esc(n.leader)}</span><span class="h">${cnt[i]||0} ${t.ent}${n.postcode?' · '+n.postcode:''}</span><span class="sc ${c}">${s==null?'—':s}</span></div>${P.nodes.some(x=>x.parent===i)?'<ul class="t">'+P.nodes.filter(x=>x.parent===i).map(x=>tr(x.id)).join('')+'</ul>':''}</li>`};
$('#tr').innerHTML='<ul class="t root">'+tr(P.root)+'</ul>';
$('#vf').innerHTML=V.bad.length||V.miss.length?`<div class="v no">✘ ${t.no} ${[...V.bad,...V.miss].join(', ')}</div>`:`<div class="v ok">✔ ${t.ok} (${V.n} ${t.ent}) · ${V.an?t.anc:t.nanc}</div>`;
const f=$('#q').value.toLowerCase(),kk=$('#k').value;$('#lt').innerHTML='<tr><th>ID</th><th>Time</th><th>Node</th><th>Kind</th><th>Actor</th><th></th><th>Hash</th></tr>'+P.ledger.filter(e=>(!kk||e.kind===kk)&&(!f||JSON.stringify(e).toLowerCase().includes(f))).reverse().map(e=>`<tr><td class="id">${e.id}</td><td>${e.at.slice(0,16).replace('T',' ')}</td><td class="id">${e.node}</td><td>${e.kind}</td><td class="id">${e.actor}</td><td>${sum(e)}</td><td class="h">${e.hash.slice(0,10)}</td></tr>`).join('')}
async function go(){$('#er').textContent='…';try{P=await openPack($('#u').value,$('#p').value);V=await verify(P);$('#lg').hidden=true;$('#app').hidden=false;draw()}catch(e){$('#er').textContent='✘ ID / password'}}
$('#go').onclick=go;$('#p').onkeydown=e=>{if(e.key==='Enter')go()};$('#q').oninput=$('#k').onchange=()=>draw();$('#out').onclick=()=>location.reload();document.querySelectorAll('[data-l]').forEach(b=>b.onclick=()=>{lang=b.dataset.l;draw()});</script></body></html>
